### PR TITLE
Ensure we don't error if `node.tagName` is undefined

### PR DESCRIPTION
**Pull request by tonyhb**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

`node.tagName`, in some cases, may end up being undefined.

### CODE REVIEW

**Comment by wooorm** [comment]
In what kind of cases do you have explicit elements, with an undefined tag name? It sounds like a bug there. And solving it here will make that problem pop up in other places?

**Comment by tonyhb** [comment]
When using shiki-twoslash a node may be produced that has no tag name.  I haven't scoured the tree to figure out exactly where this is happening and whether it's valid.  MDX produces valid JSX and only this repo has an issue, so I figured that maybe tagName being undefined is possible and we should check for it in this repo.

If an undefined tagname isn't valid... well, I can do more digging :)

**Comment by wooorm** [comment]
> whether it's valid

It’s explicitly not valid. Elements, in HTML, have a tag name. That’s why it’s [defined](https://github.com/syntax-tree/hast#element) and [typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a16317b0d61f9756ccf67c85f3e5ac4bb206fed7/types/hast/index.d.ts#L107) as required.

I am generally in favor of defensive programming, so I am not strongly opposed to this.

But, shiki(-twoslash) has several bugs, e.g., https://github.com/mdx-js/mdx/issues/2112, it’s better to solve the bugs!

**Comment by wooorm** [comment]
Ping! How do you want to go about this?

**Comment by wooorm** [comment]
Closing, `tagName`s must exist on elements according to the spec, and tons of other utilities and plugins also expect it to exist.
Thanks!

**Pull request closed without merging**
